### ISSUE TITLE
dog purchase coords

### ISSUE THREAD

**Issue by Maureks** [Dhruvpamnani/qb-k9#1]
hey ! I can't find the coords for the dog purchase!

I'am sorry if this is a dumb question, but in the readme it says it's in the config.lua!

I've tried to look on the other files , but the only coords I see is for the Lost scent function!

Thank for the attention

**Comment by Dhruvpamnani** [comment]
> hey ! I can't find the coords for the dog purchase!
> 
> I'am sorry if this is a dumb question, but in the readme it says it's in the config.lua!
> 
> I've tried to look on the other files , but the only coords I see is for the Lost scent function!
> 
> Thank for the attention

{x = 457.15, y = -1007.79, z = 28.31} you can check these coords

**Comment by Maureks** [comment]
I was just about to edit my post xD 

Sorry for the question above!

I found it , but when I take a dog , the dog is invisible , it barks even , but we just can't see it

**Comment by Dhruvpamnani** [comment]
> I was just about to edit my post xD
> 
> Sorry for the question above!
> 
> I found it , but when I take a dog , the dog is invisible , it barks even , but we just can't see it

Did you added the ped of dog

**Comment by Maureks** [comment]
no, I've only changed the model to - a_c_husky - on config and, both the first and this one, are invisible

**Comment by Dhruvpamnani** [comment]
> no, I've only changed the model to - a_c_husky - on config and, both the first and this one, are invisible

You need to add ped  it's in readme

**Comment by Dhruvpamnani** [comment]
> no, I've only changed the model to - a_c_husky - on config and, both the first and this one, are invisible
Take the ped from readme or https://github.com/Dhruvpamnani/qb-k9_ped-clothes from this

**Comment by Dhruvpamnani** [comment]
> no, I've only changed the model to - a_c_husky - on config and, both the first and this one, are invisible

Your issue is solved or not?

**Comment by Maureks** [comment]
Thanks ! the dog already appears ! I'am sorry I didn't noticed the add model thing ! Thank you ! 

But on the other way. now when giving order for the dog to search a car it gives this error : 

@qb-inventory/server/main.lua:555: bad argument #1 to 'for iterator' (table expected, got nil)

**Comment by Maureks** [comment]
Do I have to separate the functions in server.lua? Or are they just add only?

**Comment by Dhruvpamnani** [comment]
> Do I have to separate the functions in server.lua? Or are they just add only?

You need to add this  at end of the server lua

**Comment by Dhruvpamnani** [comment]
> Do I have to separate the functions in server.lua? Or are they just add only?

Try this if your issue is solved then tell me

**Comment by Maureks** [comment]
No , the same error appears , but in a different line

**Comment by Maureks** [comment]
what can I do?

**Comment by Dhruvpamnani** [comment]
> what can I do?

You are using the latest update of qb-core server

**Comment by Maureks** [comment]
yes , i've re-made from 0 the whole server with the new updates, about a week ago ,

**Comment by Dhruvpamnani** [comment]
local function HasItem(list, item)

    for i = 1, #list do

        if item == list[i] then
            return true
        end
    end

    return false
end

AddEventHandler("inventory:server:SearchLocalVehicleInventory", function(plate, list, cb)
local trunk = Trunks[plate]
local glovebox = Gloveboxes[plate]
local result = false

if trunk ~= nil then
    for k, v in pairs(trunk.items) do
        local ITEM = trunk.items[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
else
    trunk = GetOwnedVehicleItems(plate)

    for k, v in pairs(TRUNK) do

        local ITEM = TRUNK[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end

end

if glovebox ~= nil then
    for k, v in pairs(glovebox.items) do

        local ITEM = glovebox.items[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
else
    glovebox = GetOwnedVehicleGloveboxItems(plate)

    for k, v in pairs(glovebox) do
        local ITEM = glovebox[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
end
cb(RESULT)
end)

**Comment by Maureks** [comment]
ok , now it gave me this error : 

SCRIPT ERROR: @qb-inventory/server/main.lua:1641: bad argument #1 to 'for iterator' (table expected, got nil)
[ script:qb-inventory] > handler (@qb-inventory/server/main.lua:1641)
[ script:qb-inventory] > query_default (@oxmysql/dist/server/build.js:16108)
[ script:qb-inventory] > processTicksAndRejections (node:internal/process/task_queues:96)

maybe a oxmysql update that I need?

But I do think I have the latest version

**Comment by Dhruvpamnani** [comment]
> ok , now it gave me this error :
> 
> SCRIPT ERROR: @qb-inventory/server/main.lua:1641: bad argument #1 to 'for iterator' (table expected, got nil) [ script:qb-inventory] > handler (@qb-inventory/server/main.lua:1641) [ script:qb-inventory] > query_default (@oxmysql/dist/server/build.js:16108) [ script:qb-inventory] > processTicksAndRejections (node:internal/process/task_queues:96)
> 
> maybe a oxmysql update that I need?
> 
> But I do think I have the latest version

No i don't think so your oxmysql is not broken i think the code is broke wait I'm sending you the code

**Comment by Dhruvpamnani** [comment]
AddEventHandler("inventory:server:SearchLocalVehicleInventory", function(plate, list, cb)
local TRUNK = Trunks[plate]
local GLOVEBOX = Gloveboxes[plate]
local RESULT = false

if TRUNK ~= nil then
    for k, v in pairs(TRUNK.items) do
        local ITEM = TRUNK.items[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
else
    TRUNK = GetOwnedVehicleItems(plate)

    for k, v in pairs(TRUNK) do

        local ITEM = TRUNK[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end

end

if GLOVEBOX ~= nil then
    for k, v in pairs(GLOVEBOX.items) do

        local ITEM = GLOVEBOX.items[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
else
    GLOVEBOX = GetOwnedVehicleGloveboxItems(plate)

    for k, v in pairs(GLOVEBOX) do
        local ITEM = GLOVEBOX[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
end
cb(RESULT)
end)


function HasItem(list, item)

    for i = 1, #list do

        if item == list[i] then
            return true
        end
    end

    return false
end

**Comment by Dhruvpamnani** [comment]
Try this one if it's not working then I need to open my computer and put this for you 😂😂

**Comment by Maureks** [comment]
I'm going to try itnow, with a server restart as well to check better! 
Man thanks for the attention ! You're the best !

**Comment by Maureks** [comment]
It worked, it really worked ! Thank you so so so much once again ! 
Keep it up bro ! 
Much appreciated! 
P.s - You rock my dude
