### ISSUE TITLE
lj-inventory - Bad argument #1 to 'for iterator (table expected, got nil)

### ISSUE THREAD

**Issue by iplocator** [Dhruvpamnani/qb-k9#2]
**Error: Bad argument #1 to 'for iterator (table expected, got nil)**

I have followed the instructions as suggested in the readme. Our server uses lj-inventory. I get an error when commanding the K9 to search a vehicle. (see link 1)

Link 1: https://i.imgur.com/778T7Lo.png

Here is a screenshot of the code that was put into lj-inventory/server/main.lua (see link 2)

Link 2: https://i.imgur.com/0O1Ocni.png

_Any Support would be greatly appreciated!_

_Kind Regards_ - **IPL**

**Comment by Dhruvpamnani** [comment]
> **Error: Bad argument #1 to 'for iterator (table expected, got nil)**
> 
> I have followed the instructions as suggested in the readme. Our server uses lj-inventory. I get an error when commanding the K9 to search a vehicle. (see link 1)
> 
> Link 1: https://i.imgur.com/778T7Lo.png
> 
> Here is a screenshot of the code that was put into lj-inventory/server/main.lua (see link 2)
> 
> Link 2: https://i.imgur.com/0O1Ocni.png
> 
> _Any Support would be greatly appreciated!_
> 
> _Kind Regards_ - **IPL**

AddEventHandler("inventory:server:SearchLocalVehicleInventory", function(plate, list, cb)
local TRUNK = Trunks[plate]
local GLOVEBOX = Gloveboxes[plate]
local RESULT = false

if TRUNK ~= nil then
    for k, v in pairs(TRUNK.items) do
        local ITEM = TRUNK.items[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
else
    TRUNK = GetOwnedVehicleItems(plate)

    for k, v in pairs(TRUNK) do

        local ITEM = TRUNK[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end

end

if GLOVEBOX ~= nil then
    for k, v in pairs(GLOVEBOX.items) do

        local ITEM = GLOVEBOX.items[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
else
    GLOVEBOX = GetOwnedVehicleGloveboxItems(plate)

    for k, v in pairs(GLOVEBOX) do
        local ITEM = GLOVEBOX[k].name
        if HasItem(list, ITEM) then
            RESULT = true
        end
    end
end
cb(RESULT)
end)


function HasItem(list, item)

    for i = 1, #list do

        if item == list[i] then
            return true
        end
    end

    return false
end 



Use this

**Comment by Dhruvpamnani** [comment]
I will update in the readme

**Comment by iplocator** [comment]
Works, Beautiful! 

Thank you for your swift response!

_Kind Regards_ - **IPL**
